scssphp:
    enabled: '%kernel.debug%'
    autoUpdate: '%kernel.debug%'

    # site specific
    assets:
        "css/base.css":
            src: "assets/scss/base.scss"
            sourceMap: true
            # Array of import paths, relative to Symfony's project directory.
            importPaths:
                - "assets/scss"                        # main directory
        # for the gdr-histories theme
        "css/gdr-histories.css":
            src: "sites/gdr-histories/assets/scss/base.scss"
            sourceMap: true
            # Array of import paths, relative to Symfony's project directory.
            importPaths:
                - "sites/gdr-histories/assets/scss"    # theme-specific settings come first
                - "assets/scss"                        # main directory
        # for the ade theme
        "css/ade.css":
            src: "sites/ade/assets/scss/base.scss"
            sourceMap: true
            # Array of import paths, relative to Symfony's project directory.
            importPaths:
                - "sites/ade/assets/scss"              # theme-specific settings come first
                - "assets/scss"                        # main directory
