# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.locales: [de]
    locales: [de]        # without app. prefix for TeiEditionBundle
    app.default_locale: 'de'
    default_locale: 'de' # without app. prefix for TeiEditionBundle

    app.site.key: "%env(string:SITE_KEY)%"
    env(SITE_KEY): gdr

    app.site.name: "%env(string:SITE_NAME)%"
    env(SITE_NAME): 'Jüdische Geschichte[n] in der DDR'
    app.site.byline: 'Ein Interview-Portal'
    app.site.email: 'info@juedische-geschichte-online.net'
    app.site.publisher: 'Moses Mendelssohn Zentrum für europäisch-jüdische Studien'
    app.site.publisher.address: 'Am Neuen Markt 8, 14467 Potsdam'
    app.site.publisher_url: 'https://www.mmz-potsdam.de/'
    app.site.publisher_logo: 'https://www.mmz-potsdam.de/media/logo.de.svg'
    app.site.matomo.id: "%env(string:SITE_MATOMO_ID)%"
    app.public_dir: '%kernel.project_dir%/public'
    app.textrazor.options:
        api-key: "%env(string:TEXTRAZOR_API_KEY)%"
    app.zotero.options:
        api-key: "%env(string:ZOTERO_API_KEY)%"
        group-id: 5126936 # https://www.zotero.org/groups/5126936/einf%C3%BChrungsbibliographie_ddr/
    app.xsl_converter.saxonc_enable: "%env(bool:SAXONC_ENABLE)%"
    app.xsl_converter.commandline.template: "%env(string:JAVA_BIN)% -jar %kernel.project_dir%/bin/saxon9he.jar -s:%%source%% -xsl:%%xsl%% %%additional%%"
    # imagemagick settings
    # on linux, check with
    #   which convert -> /usr/bin/convert
    # on windows, set IMAGEMAGICK_PATH to your proper path,
    #   e.g. "C:/Progra~1/ImageMagick-7.1.0/"
    app.imagemagick.processor.path: "%env(string:IMAGEMAGICK_PATH)%"
    app.datacite.url: "%env(string:DATACITE_URL)%"
    app.datacite.user: SUBGOE.IGDJ
    app.datacite.password: "%env(string:DATACITE_PASSWORD)%"
    app.datacite.prefix: 10.23691
    app.datacite.funding: ~
    app.datacite.url_production_adjust: '%env(json:DATACITE_URL_PRODUCTION_ADJUST)%'

    #app.wordpress.url: 'https://ddr.juedische-geschichte-online.net/cms/'

    env(FEATURE_PREVIEW_ENV): false  # default to regular display
    app.preview: '%env(bool:FEATURE_PREVIEW_ENV)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'
            $publicDir: '%app.public_dir%'
            # we inject this into App\EventListener\ThemeRequestListener
            $siteTheme: "@= parameter('app.site.key') == 'gdr' ? (parameter('app.preview') ? 'mmz-potsdam/gdr-histories' : null) : 'mmz-potsdam/' ~ parameter('app.site.key')"
            #$wordpressBaseUrl: '%app.wordpress.url%'

    # make Controller classes in TeiEditionBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    # must come before App\ so we can override routes in App\ below
    TeiEditionBundle\Controller\:
        resource: '%kernel.project_dir%/vendor/igdj/tei-edition-bundle/src/Controller'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # override command in bundle, see https://stackoverflow.com/a/57107379
    App\Command\ArticleRefreshCommand:
        decorates: TeiEditionBundle\Command\ArticleRefreshCommand

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # The following is now registered by twig/extra-bundle
    # Twig\Extra\String\StringExtension:
    #    tags:
    #        - { name: twig.extension }

    Armin\ScssphpBundle\Twig\AssetExtension:
        arguments:
            $scssParser: '@scssphp.parser'
        tags:
            - { name: twig.extension }

    # theme selection
    App\EventListener\ThemeRequestListener:
        # arguments: ['@sylius.repository.theme', '@sylius.theme.context.settable']
        tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # So we can inject @solr.client, see https://github.com/floriansemm/SolrBundle/issues/191#issuecomment-466101623
    FS\SolrBundle\SolrInterface: '@solr.client'

    App\Service\ZoteroApiService:
        arguments:
            $options: "%app.zotero.options%"

    App\Menu\Builder:
        arguments: [ "@knp_menu.factory", "@translator.default", "@request_stack", "@router", "@twig"  ]
        tags:
            # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createTopMenu, alias: top }
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createBreadcrumbMenu, alias: breadcrumb }
            - { name: knp_menu.menu_builder, method: createFooterMainMenu, alias: footer-main }
